import type { Event } from "../types/event";
import { ethers } from "ethers";

export const MOCK_EVENTS: Event[] = [
  {
    id: 0,
    name: "Travis Scott – Utopia World Tour",
    description:
      "Travis Scott brings the Utopia World Tour to life with stunning visuals, surprise guests, and a set list spanning his entire discography.",
    venue: "Madison Square Garden",
    city: "New York, NY",
    date: "2026-04-12T20:00:00Z",
    imageUrl: "",
    maxTickets: 500,
    soldCount: 423,
    priceWei: ethers.parseEther("0.05").toString(),
    priceEth: "0.05",
    category: "concert",
    artist: "Travis Scott",
    exists: true,
  },
  {
    id: 1,
    name: "Billie Eilish – Hit Me Hard And Soft Tour",
    description:
      "Intimate and immersive, Billie Eilish performs her latest album in full alongside fan favourites from her entire catalogue.",
    venue: "O2 Arena",
    city: "London, UK",
    date: "2026-05-03T19:00:00Z",
    imageUrl: "",
    maxTickets: 800,
    soldCount: 800,
    priceWei: ethers.parseEther("0.08").toString(),
    priceEth: "0.08",
    category: "concert",
    artist: "Billie Eilish",
    exists: true,
  },
  {
    id: 2,
    name: "Kendrick Lamar – GNX Tour",
    description:
      "Kendrick Lamar celebrates GNX with a full production show including live band, dancers, and surprise set pieces.",
    venue: "Kia Forum",
    city: "Los Angeles, CA",
    date: "2026-06-20T21:00:00Z",
    imageUrl: "",
    maxTickets: 1000,
    soldCount: 312,
    priceWei: ethers.parseEther("0.1").toString(),
    priceEth: "0.1",
    category: "concert",
    artist: "Kendrick Lamar",
    exists: true,
  },
  {
    id: 3,
    name: "Doja Cat – Scarlet Tour",
    description:
      "Doja Cat's Scarlet Tour is a theatrical, costume-heavy spectacle unlike anything seen in pop concerts.",
    venue: "Accor Arena",
    city: "Paris, FR",
    date: "2026-07-08T20:30:00Z",
    imageUrl: "",
    maxTickets: 600,
    soldCount: 201,
    priceWei: ethers.parseEther("0.06").toString(),
    priceEth: "0.06",
    category: "concert",
    artist: "Doja Cat",
    exists: true,
  },
  {
    id: 4,
    name: "The Weeknd – After Hours Til Dawn",
    description:
      "The Weeknd's most ambitious tour yet — a two-part show blending After Hours and Dawn FM into one continuous narrative.",
    venue: "Rogers Centre",
    city: "Toronto, CA",
    date: "2026-08-15T20:00:00Z",
    imageUrl: "",
    maxTickets: 1200,
    soldCount: 50,
    priceWei: ethers.parseEther("0.12").toString(),
    priceEth: "0.12",
    category: "concert",
    artist: "The Weeknd",
    exists: true,
  },
  {
    id: 5,
    name: "SZA – SOS World Tour",
    description:
      "SZA performs her Grammy-winning SOS in full for the final leg of her record-breaking world tour.",
    venue: "United Center",
    city: "Chicago, IL",
    date: "2026-09-01T19:30:00Z",
    imageUrl: "",
    maxTickets: 700,
    soldCount: 699,
    priceWei: ethers.parseEther("0.07").toString(),
    priceEth: "0.07",
    category: "concert",
    artist: "SZA",
    exists: true,
  },
];
